[package]
name = "basic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="output"
crate-type = ["dylib"]

[dependencies]
once_cell = "1.8.0"
raylib = "3.7.0"